### ISSUE TITLE
serviceusage.googleapis.com

### ISSUE THREAD

**Issue by bdelv** [terraform-google-modules/terraform-google-bootstrap#10]
I have the impression that the **serviceusage.googleapis.com** API should be enabled in the seed project in order to later be able to enable services in the new projects using the terraform-sa.

If true, maybe adding it in the default of **"activate_apis"** in **variables.tf** might make sense 

> variable "activate_apis" {
>   description = "List of APIs to enable in the seed project."
>   type        = list(string)
> 
>   default = [
>     "**serviceusage.googleapis.com**"
>     "servicenetworking.googleapis.com",
> ...

If false, then ... sorry for the disturbance. :)

**Comment by morgante** [comment]
Yes, I think activating this API makes sense. Would you mind opening a PR?

**Comment by bdelv** [comment]
Sure. Will do after work.

**Comment by bdelv** [comment]
PR merged. Closing.
Thx
