### ISSUE TITLE
Remove bootstrap test in org mode

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-bootstrap#104]
[simple](https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/test/fixtures/simple) test creates projects under the org and is not auto cleaned up. We should consider dropping this and just using [simple-folder](https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/test/fixtures/simple-folder) and patch [cloud build example](https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/3c21b4695f3a48314bab3ff3804e38f853b1afd1/examples/cloudbuild_enabled/main.tf#L38) also to use bootstrap in folder mode.

**Comment by rjerrems** [comment]
Is there a way we can target it for cleanup by adding labels/tags/naming in a certain way? It would be good to continue to test at the org level, as this is a key use case for the module.

**Comment by bharathkkb** [comment]
@rjerrems I can look into doing cleanup at the org level by modifying the [existing cleanup function](https://github.com/terraform-google-modules/terraform-google-scheduled-function/tree/f31b57ffd6dedf621fb1a2770a5e91ae0cf9fcd4/modules/project_cleanup). Since there is relatively low volume of activity (and hence failed tests) we could also just have a one off CB job that we trigger on a schedule to do a root project cleanup.
