### ISSUE TITLE
Terraform Runner images do not have curl

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-bootstrap#105]
We should update the runner images to have curl as it is required for usage with modules that use [gcloud wrapper](https://github.com/terraform-google-modules/terraform-google-gcloud#software). @rjerrems any reason why we decided not to? https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/3c21b4695f3a48314bab3ff3804e38f853b1afd1/modules/cloudbuild/cloudbuild_builder/Dockerfile#L37

x-ref: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/878

**Comment by rjerrems** [comment]
I believe that was removed initially in order to keep the image leaner, but I don't see any issue leaving curl in the image.

**Comment by bharathkkb** [comment]
Thanks for the quick fix @rjerrems
