### ISSUE TITLE
Combination with  cloud-foundation-fabric

### ISSUE THREAD

**Issue by wmuizelaar** [terraform-google-modules/terraform-google-bootstrap#11]
Hi,

What would be the best way to integrate this bootstrap procedure with the examples as provided in https://github.com/terraform-google-modules/cloud-foundation-fabric ?

**Comment by rjerrems** [comment]
G'day @wmuizelaar - can you please elaborate a little more on what you are trying to do and I will see if I can help? Which examples from the fabric repo are you most interested in using?

**Comment by gilesw-vion** [comment]
I'm interested in this also ... bootstrapping a new GCP account coming from AWS with a fairly complex org. The examples in [https://github.com/terraform-google-modules/cloud-foundation-fabric] are great for organisational structure but they bootstrap terraform without using this module. This module seems preferable for getting a clean start to an account and observing good practices with regard to iam roles and groups etc.
I'm particularly looking at business unit example in the fabric repo.

**Comment by rjerrems** [comment]
Thanks @gilesw-vion - currently the cloud foundation fabric codebase has its own lightweight bootstrapping for setting up terraform. For example usage of this module and an example terraform foundations, keep an eye on this repo as we will be updating it in the near future. https://github.com/terraform-google-modules/terraform-example-foundation
