### ISSUE TITLE
State bucket not found

### ISSUE THREAD

**Issue by bdubaut** [terraform-google-modules/terraform-google-bootstrap#111]
Hi, 
I have beet trying to use the module, and the local application of changes with `terraform apply` functions correctly. I end up with the following structure:
```
org
   └── folder
      └── project
         └── state-bucket
```

However, when creating my `backend.tf` file and that I try to run `terraform init -migrate-state` or `-reconfigure`, I get the following error:

```
❯ terraform init -migrate-state
Initializing modules...

Initializing the backend...
╷
│ Error: Error inspecting states in the "gcs" backend:
│     querying Cloud Storage failed: storage: bucket doesn't exist
│ 
│ Prior to changing backends, Terraform inspects the source and destination
│ states to determine what kind of migration steps need to be taken, if any.
│ Terraform failed to load the states. The data in both the source and the
│ destination remain unmodified. Please resolve the above error and try again.
│ 
│ 
```

My backend configuration is as follows:
```hcl
terraform {
  backend "gcs" {
    bucket = "<existing bucket name>"
  }
}
```

What am I doing wrong?

### Versions

- Terraform 1.0.0
- google cloud provider 3.75.0
- `random` provider 2.2
- `null` provider 2.1
- Google Cloud SDK 349.0.0
- beta 2021.07.19
- bq 2.0.70
- core 2021.07.19
- gsutil 4.65

**Comment by rjerrems** [comment]
hi @bdubaut - are you able to confirm that the bucket you are referencing exists? Is this an existing bucket or the bucket created by the bootstrap terraform?

We have some instructions here that we use for example foundation if that is helpful:

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#deploying-with-cloud-build

**Comment by bdubaut** [comment]
@rjerrems Yes the bucket is the one created by the module after I run `terraform apply` the first time. I can find the bucket in the gcloud console, and by running `gsutil ls -p seed-project-id`

**Comment by bdubaut** [comment]
@rjerrems FYI this is how I used the bootstrap module
```hcl
locals {
  parent = var.parent_folder != "" ? "folders/${var.parent_folder}" : "organizations/${var.org_id}"
}

resource "google_folder" "bootstrap" {
  display_name = "infra-bootstrap"
  parent       = local.parent
}

module "seed_bootstrap" {
  source               = "terraform-google-modules/bootstrap/google"
  version              = "2.3.1"
  org_id               = var.org_id
  parent_folder        = var.parent_folder == "" ? "" : local.parent
  billing_account      = var.billing_account
  default_region       = var.default_region
  group_billing_admins = "<email address for billing admins group>"
  group_org_admins     = "<email address for org admins group>"
  project_prefix       = var.project_prefix
}
```

**Comment by rjerrems** [comment]
Does the user which terraform is running as have access to read/write to the bucket? You can also refresh credentials with the correct user with `gcloud auth application-default login`

I am also assuming that your state is local which you are trying to migrate? 

It may also be worthwhile creating a new test terraform configuration, with the same backend set to see if it works on a fresh run without any state. (you could just do data lookups if you don't want to create any resources)

Failing all of that, you could potentially upload the state file to the bucket yourself using gsutil and see if this works.

**Comment by bdubaut** [comment]
Ah maybe I should use the created service account from the initial seed bootstrap

**Comment by rjerrems** [comment]
The module itself is intended to be run by a user as one of the first steps to bootstrap an org, who is in the `group_org_admins` group FYI

**Comment by bdubaut** [comment]
@rjerrems Yes, that is what I am trying to do indeed. My understanding is that once ran, this module should not change at all (or very little), as the bulk of the changes happens in the following (automated via CI) steps like folders, networking, etc.

**Comment by bdubaut** [comment]
It worked fine! thanks a lot @rjerrems 🤗
