### ISSUE TITLE
Terraform Validator v0.6.0 change to release binary format not handled by Cloud Build builder Dockerfile

### ISSUE THREAD

**Issue by timantrobus** [terraform-google-modules/terraform-google-bootstrap#117]
The `v0.6.0` release of Terraform Validator changes the format of the release binaries to a zipped tarball per these release notes : https://github.com/GoogleCloudPlatform/terraform-validator/releases/tag/v0.6.0

This also means the file names of the release binaries available in GCS have changed since version `0.5.1`. See the below example illustrating the difference :

- __v0.5.1__ : `gs://terraform-validator/releases/v0.5.1/terraform-validator-linux-amd64`
- __v0.6.0__ : `gs://terraform-validator/releases/v0.6.0/terraform-validator_linux_amd64-0.6.0.tar.gz`

This change is currently not supported by the [Cloud Build builder Dockerfile](https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/cloudbuild_builder/Dockerfile) and results in a build error indicating it cannot find the terraform-validator binary.

Also the Dockerfile will need to be amended to unzip and extract the tarball as it only unzips it currently.

**Comment by rjerrems** [comment]
makes sense to me @timantrobus - would you mind creating a PR to make this work?

cc @bharathkkb FYI

**Comment by timantrobus** [comment]
Thanks for the feedback @rjerrems. 

I'm on holiday now until 1st September but am happy to raise a PR for this change when I get back if the issue has not already been resolved by then 👍

**Comment by timantrobus** [comment]
Hi @rjerrems : FYI I've raised PR #121 with a proposed fix for this issue.
