### ISSUE TITLE
Different escape character in Windows

### ISSUE THREAD

**Issue by ouissameb** [terraform-google-modules/terraform-google-bootstrap#130]
Hi,

There is an error when running `gcloud builds submit [...]` in Windows environments.
PowerShell and CMD prompts in Windows have different escape characters than Bash in Linux.

- CMD: ^
- Powershell: `
- Bash: \

The easiest way to fix it I think is to make the command a one-liner to fit all language runtimes, it will however be at the expense of making the command less comfortable to read, I still believe it is worth it.

I think @philip-harvey this is the issue you encountered when you raised this issue https://github.com/terraform-google-modules/terraform-example-foundation/issues/544 a few weeks ago. @bharathkkb 

Let me  know  what you  think and I can make the change

**Comment by bharathkkb** [comment]
Hi @ouissameb 

Is running TF via WSL2 an option for you? We haven't seen too many requests for running in Windows which is why I am a bit hesitant on sacrificing readability.

**Comment by philip-harvey** [comment]
I support fixing this so it will work on Windows, this is the only thing I have found so far that doesn't work under Windows.

**Comment by ouissameb** [comment]
As long as we are running Windows 10 version 1903+/2004+, WSL remains an option yes but it is always nice to have it run natively, knowing that WSL is not installed by default and it might be a little overkill to install it just for this purpose.
If it is the only remaining issue with Windows so far, it might just be okay to scroll right a little bit for this particular command.
N.B: I also see your point that we should prioritize issues based on actual user needs.

**Comment by bharathkkb** [comment]
Discussed with @ouissameb offline. We think its a small patch and @ouissameb agreed look into submitting a PR!
