### ISSUE TITLE
Cloudbuild submodule: change Terraform version

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-bootstrap#16]
It is currently impossible to change the Terraform version used in the CloudBuild pipeline because it is harcoded as an env variable [here](https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/cloudbuild_builder/Dockerfile).

**Comment by rjerrems** [comment]
Agree - would be good to parameterize this. Do you have time to try and implement a solution @ocervell ?

**Comment by rjerrems** [comment]
I am thinking we paramaterize the `TERRAFORM_VERSION_SHA256SUM` and `TERRAFORM_VERSION` with a default value, that people can override if they want a specific version?
