### ISSUE TITLE
Impersonation example

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-bootstrap#20]
Currently I haven't been able to set up impersonation of the CFT service account. 

I'm running the builds with the default CloudBuild service account and there seems to be no way to use a different one without 1. passing the credentials to the YAML file or 2. running `gcloud` impersonation commands in the pipeline itself, so I'm curious how this would work. 

Could we give an example `cloudbuild.yaml` config that uses the variables passed [here](https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/main.tf#L167) (e.g: using `TF_SERVICE_ACCOUNT` variable) for users to follow easily ?

**Comment by rjerrems** [comment]
Good point, in the interim examples coming here demonstrate how to use impersonation through both cloud build and the provider configuration (you need both):

https://github.com/terraform-google-modules/terraform-example-foundation/pull/2/files
