### ISSUE TITLE
Documentation - How to use/Best Practices

### ISSUE THREAD

**Issue by eahrend** [terraform-google-modules/terraform-google-bootstrap#200]
### TL;DR

Previously when bootstrapping an org for IAC, I used a bash script that would control the seed project and create a state bucket, however this module seems to do this. 

My question is, where should I store the state for this module as I'm assuming I won't have bucket created for this module to store it's state in.

**Comment by dlprada** [comment]
I suppose the first time it has to be manually executed locally, using the local backend, then just create a `backend.tf` pointing to the newly created bucket, as soon as you run the `init` command again it will ask if you want to migrate the local state to the bucket.
