### ISSUE TITLE
Allow user to control resource names

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-bootstrap#23]
The current project and state bucket resources get random characters appended to their name. There should be a way to bypass this and explicitly set any desired resource names.

**Comment by rjerrems** [comment]
That sounds fair enough to me - do you think something like the `random_project_id` flag used in the project factory module https://github.com/terraform-google-modules/terraform-google-project-factory? If so we could potentially introduce something like `random_resource_id` or `random_resource_suffix`

**Comment by umairidris** [comment]
The API I had in mind was was vars such as `project_id` (mutually exclusive with `project_prefix`), `state_bucket` (which can have fields name, location, labels), etc.

If project_id or state_bucket.name is set then use that, else use the randomization logic.

WDYT?

**Comment by rjerrems** [comment]
Yeah I think that makes sense, any chance you would have bandwith to do a PR? We could probably discard the project prefix is adding the additional variables

**Comment by umairidris** [comment]
Sure I can take a look next week or so. Thanks!

**Comment by rjerrems** [comment]
Great thanks!

**Comment by rjerrems** [comment]
It is now possible to set both the project ID and state bucket name so will close this
