### ISSUE TITLE
Allow using the Terraform image without using CloudBuild

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-bootstrap#27]
Customers would like to use and push the Terraform image to GCR for use with other CICD systems, such as Gitlab CI, without having to set up all the Cloud Build stuff. 

Could we split the `cloudbuild_builder` folder inside the `cloudbuild` submodule into it's own submodule ? 

Or even better, use the image that is available from the cloud-builders-community repo [here](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/terraform) and improve it if needed ?

**Comment by rjerrems** [comment]
G'day @ocervell - can you elaborate on the use case a little more? the reason I ask, is that if a customer wants to create a terraform builder from gcloud as a standalone, I would probably recommend they use the community builder.

Are you looking for a submodule you can call in terraform that abstracts just this functionality only? If so we could potentially look at doing this.

**Comment by ocervell** [comment]
Sorry if I was unclear, I guess those are two separate issues:

1) It's confusing for customers if they should use this Terraform build (we push for CFT in PSO) or the community one

2) Customer has Gitlab CI but still wants to use the terraform-google-bootstrap module and likes the way we're building the Terraform image from the module, so they would like to use only the portion to build the Terraform image, but not the CloudBuild stuff. 

So, to answer your question, yes, a submodule to build the TF image would be nice, that we could also call from our CloudBuild module.

**Comment by rjerrems** [comment]
Aha I get what you are saying, if the customer likes the image without cloud build extras, the cloud build file YAML and Dockerfile can both be used in isolation to create a copy of the image. (no dependency on terraform) Perhaps we could also solve this by add some docs explaining how to use it in isolation?

The image we have created was originally built from the community builder, but the two have drifted apart slightly. It would be nice to use the community builder, but we do also need to make sure that we have self contained / stable dependencies as well.
