### ISSUE TITLE
Why are values for org_id and folder_id  mutually exclusive?

### ISSUE THREAD

**Issue by sbadakhc** [terraform-google-modules/terraform-google-bootstrap#29]
What is the rational for making org_id and folder_id mutually exclusive. I think it makes sense to have both and also perhaps have the option to provision multiple folders?
```
module.seed_project.module.project-factory.google_project.main: Modifying... [id=projects/cft-seed-5e02]

Error: 'org_id' and 'folder_id' cannot be both set.

  on .terraform/modules/seed_project/terraform-google-project-factory-7.1.0/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {
```

**Comment by rjerrems** [comment]
Hi @sbadakhc - can you please elaborate a little on the folder structure you are trying to create so I can better understand the problem? Can you share the value you are using for `folder_id` ?

**Comment by sbadakhc** [comment]
HI @rjerrems - Sure. I have a use case that entails creating an organisation with multiple folders which map to business operations like sales, marketing, technology etc. These departments have their own infrastructure and resources but likely to be accessible to each other via a shared vpc. I'm pretty much just following the docs here https://cloud.google.com/resource-manager/docs/creating-managing-folders. I would like the ability to boot strap a org with multiple folders or have a way of adding folders once I have one department setup. Thanks for your assistance. I would be happy to provide more details. Also is there slack channel available to discuss these issues in real-time?

**Comment by rjerrems** [comment]
Hi @sbadakhc - we don't have a live channel available unfortunately. Can you share the code snippet you are running which is producing this error?

**Comment by sbadakhc** [comment]
Ah think I got my wires crossed. Does it make sense to have a folder factory module to accomplish?

**Comment by rjerrems** [comment]
Yeah that makes sense. If you are looking for a module to help manage folders, this might prove useful for you:

https://github.com/terraform-google-modules/terraform-google-folders

Although it is worth noting that creating folders is usually quite straight forward, if you are not doing anything else on top of that (IAM etc). As an example, this creates on parent folder and three child folders:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/1-org/folders.tf

Hope this helps

**Comment by sbadakhc** [comment]
@rjerrems thanks. I'll take a look as advised. With regards to the process outlined above, is it inline with what you attempting here?
