### ISSUE TITLE
Project Name as Output

### ISSUE THREAD

**Issue by anjil** [terraform-google-modules/terraform-google-bootstrap#30]
Hi All,
I am using the terraform-google-bootstrap module as a source in my local module as below
```
module "bootstrap" {
  source  = "terraform-google-modules/bootstrap/google"
  version = "~> 1.0"

  org_id               = var.organization_id
  billing_account      = var.billing_account
  group_org_admins     = var.group_org_admins
  group_billing_admins = var.group_billing_admins
  default_region       = var.default_region
  project_prefix       = var.project_prefix
}
```

Now in the https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/outputs.tf file there is no block for `project_name`.
I don't want to download this module locally and change the output file.
Please suggest how can I get the project name?

Thanks in advance.

**Comment by rjerrems** [comment]
Hi @anjil thanks for the report - what are you using the project name for? For most use cases, the project id which is an output is sufficient (for creating other resources etc)

**Comment by bharathkkb** [comment]
On a side note, with the `seed_project_id` you should be able to get the project name using the `google_project` [data resource](https://www.terraform.io/docs/providers/google/d/google_project.html).
```tf
data "google_project" "project" {
  project_id = module.bootstrap.seed_project_id
}
```
and then the name should be accessible at `data.google_project.project.name`.

**Comment by anjil** [comment]
@bharathkkb Perfect , this works for me. Thanks mate 👍
