### ISSUE TITLE
Cloudbuild module to run after bootstrap module

### ISSUE THREAD

**Issue by anjil** [terraform-google-modules/terraform-google-bootstrap#31]
Hi All,
I am using `terraform-google-bootstrap` to provision resources from this module. Now, I want to use the `cloudbuild` module but it should not create new project. All the resources of `cloudbuild` should provision inside the project created by `terraform-google-bootstrap` module.
My main.tf file looks as below

```
module "bootstrap" {
  source  = "terraform-google-modules/bootstrap/google"
  version = "~> 1.0"

  org_id               = var.organization_id
  billing_account      = var.billing_account
  group_org_admins     = var.group_org_admins
  group_billing_admins = var.group_billing_admins
  default_region       = var.default_region
  project_prefix       = var.project_prefix
}

data "google_project" "seed_project" {
  project_id = module.bootstrap.seed_project_id
  depends_on = [
    module.bootstrap
  ]
}


module "cloudbuild_bootstrap" {
  source  = "./modules/cloudbuild"
  
  org_id                  = var.organization_id
  project_id              = module.bootstrap.seed_project_id
  project_number          = data.google_project.seed_project.number
  billing_account         = var.billing_account
  group_org_admins        = var.billing_account
  default_region          = var.default_region
  sa_enable_impersonation = true
  terraform_sa_email      = module.bootstrap.terraform_sa_email
  terraform_sa_name       = module.bootstrap.terraform_sa_name
  terraform_state_bucket  = module.bootstrap.gcs_bucket_tfstate
}
```

Please suggest how Can I make `cloudbuild_bootstrap` module to run after `bootstrap`

Thanks in advance .

**Comment by rjerrems** [comment]
Hi @anjil we have a couple of examples:

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap

And in this repos examples here:

https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/examples/cloudbuild_enabled

Right now, there is no way to create a single project and put all resources in it - the two projects are intentionally separated for the main bootstrap / service accounts and the cloud build project.

Hope this helps
