### ISSUE TITLE
Referenced Google module `kms` which is enforcing  hashicorp/google < 6

### ISSUE THREAD

**Issue by ruiteix** [terraform-google-modules/terraform-google-bootstrap#319]
### TL;DR

https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/main.tf#L113C14-L113C49

references

```
  source  = "terraform-google-modules/kms/google"
  version = "~> 2.1"
```

which has https://github.com/terraform-google-modules/terraform-google-kms/blob/v2.3.0/versions.tf#L23

```
    google = {
      source  = "hashicorp/google"
      version = ">= 3.53, < 6"
    }
  }
```

Needs https://github.com/terraform-google-modules/terraform-google-kms/pull/152 to be merged

**Comment by apeabody** [comment]
https://github.com/terraform-google-modules/terraform-google-kms/pull/152 has been merged
