### ISSUE TITLE
Support folder level

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-bootstrap#32]
Currently this module sets up a devops type project and service account for CICD at an org level. It can be useful to also set this up at a folder level.

Larger orgs will want to break their devops at different layers so that a single service account does not manage the entire org.

Would you consider a change alongside #23 to specify a parent_type (default to organization) and parent_id similar to other CFT modules that support deploying resources at both org and folder level?

**Comment by morgante** [comment]
This seems sensible.

**Comment by rjerrems** [comment]
Yeah sounds sensible to me as well.

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/40
