### ISSUE TITLE
Option to switch between binding vs member for project_creator

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-bootstrap#38]
Currently we require this workaround https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/853b5110539581fee7226ec7331ad57fe702c90a/build/int.cloudbuild.yaml#L35 for testability. Is there a reason behind why we cant have a flag like `var.authoritative` to switch between additive vs authoritative?

```tf


resource "google_organization_iam_binding" "project_creator" {
  count = var.authoritative ? 1 : 0
  org_id  = var.org_id
  role    = "roles/resourcemanager.projectCreator"
  members = local.org_project_creators
}


resource "google_organization_iam_member" "project_creator" {
  for_each = var.authoritative ? toset([]) : local.org_project_creators
  org_id   = var.org_id
  role     = "roles/resourcemanager.projectCreator"
  member   = each.key
}

**Comment by morgante** [comment]
I'd rather keep the module interface simple. 

For testing purposes, we should just put the test service account in the project creators group.

**Comment by bharathkkb** [comment]
@morgante sounds good. I synced with @rjerrems offline and will be testing similar to bootstrap.
