### ISSUE TITLE
Relax versioning for Terraform 0.13

### ISSUE THREAD

**Issue by pinglin** [terraform-google-modules/terraform-google-bootstrap#55]
Wondering if this module can also be relaxed like [terraform-google-project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/examples/budget_project/versions.tf#L18)? Thanks.

**Comment by rjerrems** [comment]
Thanks @pinglin - quite possibly, we will just need to verify that the module is working as expected on version 0.13

cc @bharathkkb any thoughts?

**Comment by bharathkkb** [comment]
@rjerrems yeah we should be able to relax. I dont think there are any internal dependencies other than PF, so we should also bump that to the relaxed `9.0` release and this should work.

**Comment by michaeldeman** [comment]
I did a smoke test on this locally with known/working code we use with terraform 0.12.x.
Using Terraform v0.13.4:

Updating project-factory dependency to 9.0.0 works.

Updating project-factory dependency to 9.1.0 does NOT work and fails with the below.  I see a recent commit there to restore some behavior so hopefully that is the fix and a project-factory 9.1.1 will be out soon that resolves this?

SNIP
Initializing modules...
Downloading terraform-google-modules/project-factory/google 9.1.0 for seed_bootstrap.seed_project...
SNIP
Error: Invalid resource type

  on .terraform/modules/seed_bootstrap.seed_project/modules/project_services/main.tf line 38, in resource "google_project_service_identity" "project_service_identities":
  38: resource "google_project_service_identity" "project_service_identities" {

The provider provider.google-beta does not support resource type
"google_project_service_identity".
SNIP

**Comment by bharathkkb** [comment]
Hi @michaeldeman 
Could you test with the provider to >= 3.38.0  which supports `google_project_service_identity`

**Comment by michaeldeman** [comment]
Hi @bharathkkb - good call on the google provider version, I was pinned to 3.31.x locally.

Running against project-factory 9.1 with google and google-beta 3.38.0 worked; and 3.43.0 also worked.
There were two deprecation warnings (one an attribute, another just syntax) that probably should be tidied up.

**Comment by rjerrems** [comment]
This should be resolved now by https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/67
