### ISSUE TITLE
Terraform and Terraform Validator are out of date

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-google-bootstrap#70]
In the [cloudbuild_builder](https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/modules/cloudbuild/cloudbuild_builder) module, it is currently pinned to terraform 0.12.24 and terraform-validator 2020-03-05.  The current versions are 0.12.29 and 2020-09-24 respectively.

**Comment by rjerrems** [comment]
Thanks for the report & PR - this should be fixed in latest release!
