### ISSUE TITLE
Custom project ID for seed project

### ISSUE THREAD

**Issue by bborysenko** [terraform-google-modules/terraform-google-bootstrap#73]
It will be great to be able to use custom seed project id. For the moment, we can override `project_prefix`, but not the overall seed project id. It might be a case where we need to follow some naming conventions. For example, we are going to use something like `prj-tfstate` to manage foundation resources and `prj-<business-unit-code>-tfstate` for resources specific to the business unit.

**Comment by bharathkkb** [comment]
fixed via #74
