### ISSUE TITLE
Executing from Windows Host Fails

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-bootstrap#75]
This was discovered on a customer call, and I don't have a full error trace. Apologies.

[`terraform-google-gcloud`](https://github.com/terraform-google-modules/terraform-google-gcloud) is [called](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/79f7c953a5267b0d22c2e9396136e27319320ae0/modules/core_project_factory/main.tf#L188) by [`terraform-google-project-factory`](https://github.com/terraform-google-modules/terraform-google-project-factory) when `default_service_account == "disable"`, which is its default value. [`terraform-google-bootstrap`](https://github.com/terraform-google-modules/terraform-google-bootstrap) does not allow overriding that parameter into `terraform-google-project-factory` parameter.

`terraform-google/modules/gcloud/google` calls a Bash [script](https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/scripts/check_env.sh), which causes execution from Windows machines to fail. The dependency on *nix, while reasonable, is not documented.

I'd suggest the following as a rapid remediation:

1. Allow overriding the value of `default_service_account` from an input to this module
2. Document in `terraform-google-gcloud` and `terraform-google-project-factory`, and their downstreams (including this module), that execution from Windows is not supported.

**Comment by bharathkkb** [comment]
Yeah this could have been made clearer. FWIW we are getting rid of this for next major release with an ETA of ~2 weeks being tracked here: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/408

**Comment by beingminimal** [comment]
What is the current status of this issue?
I am also receiving the same error when I try to bootstrap the environment from my machine

Error: failed to execute ".terraform/modules/cloudbuild_bootstrap.cloudbuild_project.project-factory.gcloud_disable/scripts/check_env.sh": fork/exec .terraform/modules/cloudbuild_bootstrap.cloudbuild_project.project-factory.gcloud_disable/scripts/check_env.sh: %1 is not a valid Win32 application.

**Comment by bharathkkb** [comment]
will be fixed by #81

**Comment by bharathkkb** [comment]
fixed via #81
