### ISSUE TITLE
SCC SHA yields "KMS_KEY_NOT_ROTATED" on tf-key resource

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-bootstrap#77]
No rotation period is set on the [`tf-key`](tf-key) resource, which triggers a SCC finding `KMS_KEY_NOT_ROTATED`. Suggest allowing a retention period to be set (or a best-practice default provided).

**Comment by rjerrems** [comment]
This makes sense, would be happy to accept a PR if you have the time?

@bharathkkb FYI

**Comment by Jberlinsky** [comment]
I filed the issue as a reminder-to-self to submit a PR when I have a moment :)

**Comment by rjerrems** [comment]
Great thanks @Jberlinsky

**Comment by bharathkkb** [comment]
Opening to track removal of KMS resources https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/2b9bf2cdfa99ef098b4816a941733d34b023e45b/modules/cloudbuild/main.tf#L85 for https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/142 breaking release
