### ISSUE TITLE
Misleading code in cloudbuild module

### ISSUE THREAD

**Issue by ipv1337** [terraform-google-modules/terraform-google-bootstrap#82]
In the code https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/main.tf lines 187 and 219 show:
'''
_SEED_PROJECT_ID      = module.cloudbuild_project.project_id
'''

Shouldn't it be:
'''
_SEED_PROJECT_ID      = module.seed_bootstrap.seed_project_id
'''

Does not look like terraform-example-foundation even uses this parameter, but still it's confusing should someone actually start using it as I was looking to leverage the cloudbuild module else in our codebase. Of course we also extended this module to support GitHub as GCP repos do not have a review workflow built in.

**Comment by rjerrems** [comment]
Hi @ipv1337 - thanks for picking this up, this is incorrect. Currently the seed project id is not provided explicitly to the cloudbuild module, so it probably makes sense to add a variable for this or remove this substitution altogether. Do you have a use case for using this project ID in your builds? The substitutions were created for convenience but as you alluded to, the example foundation only uses some of them.

**Comment by rjerrems** [comment]
For now I have removed that substitution @ipv1337 - if you have a strong requirement for project ids, feel free to share here.

**Comment by ipv1337** [comment]
Thanks and sorry I wasn't able to respond in a timely manner. 

No I don't have a need for the substitution. Just thought I'd post the question and help cleanup if it wasn't needed by anyone else since I was in this area of the code while borrowing some ideas used here for standing up some CI/CD for our use of Cloud Run and Composer.
